version: "3"

services:
  db:
    image: mysql:5.7.21
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
